/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Sat May 30 20:59:48 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkIvyAdd_h__
#define __mkIvyAdd_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkIvyAdd module */
class MOD_mkIvyAdd : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_reduced;
  MOD_Reg<tUInt64> INST_result;
  MOD_Reg<tUInt64> INST_wire0;
  MOD_Reg<tUInt64> INST_wire1;
 
 /* Constructor */
 public:
  MOD_mkIvyAdd(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_reduced__h197;
  tUInt64 DEF_wire1___d4;
  tUInt64 DEF_wire0___d1;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_rl_n32_add();
  void RL_rl_erase();
 
 /* Methods */
 public:
  tUInt8 METH_done();
  tUInt8 METH_RDY_done();
  tUInt32 METH_readResult();
  tUInt8 METH_RDY_readResult();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkIvyAdd &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkIvyAdd &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkIvyAdd &backing);
};

#endif /* ifndef __mkIvyAdd_h__ */
