/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Sun May 31 19:52:54 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkIvyAdd.h"


/* String declarations */
static std::string const __str_literal_2("rl_erase fired: discarded token on wire1", 40u);
static std::string const __str_literal_1("rl_n32_add fired: %0d + %0d = %0d", 33u);


/* Constructor */
MOD_mkIvyAdd::MOD_mkIvyAdd(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_reduced(simHdl, "reduced", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_result(simHdl, "result", this, 34u, 12884901888llu, (tUInt8)0u),
    INST_wire0(simHdl, "wire0", this, 34u, 4294967311llu, (tUInt8)0u),
    INST_wire1(simHdl, "wire1", this, 34u, 4294967308llu, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 7u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkIvyAdd::init_symbols_0()
{
  init_symbol(&symbols[0u], "RL_rl_erase", SYM_RULE);
  init_symbol(&symbols[1u], "RL_rl_n32_add", SYM_RULE);
  init_symbol(&symbols[2u], "reduced", SYM_MODULE, &INST_reduced);
  init_symbol(&symbols[3u], "reduced__h197", SYM_DEF, &DEF_reduced__h197, 1u);
  init_symbol(&symbols[4u], "result", SYM_MODULE, &INST_result);
  init_symbol(&symbols[5u], "wire0", SYM_MODULE, &INST_wire0);
  init_symbol(&symbols[6u], "wire1", SYM_MODULE, &INST_wire1);
}


/* Rule actions */

void MOD_mkIvyAdd::RL_rl_n32_add()
{
  tUInt32 DEF_sum__h202;
  tUInt64 DEF__1_CONCAT_wire0_BITS_31_TO_0_1_PLUS_wire1_BITS__ETC___d14;
  tUInt32 DEF_b__h201;
  tUInt32 DEF_a__h200;
  DEF_wire1___d4 = INST_wire1.METH_read();
  DEF_wire0___d1 = INST_wire0.METH_read();
  DEF_a__h200 = (tUInt32)(DEF_wire0___d1);
  DEF_b__h201 = (tUInt32)(DEF_wire1___d4);
  DEF_sum__h202 = DEF_a__h200 + DEF_b__h201;
  DEF__1_CONCAT_wire0_BITS_31_TO_0_1_PLUS_wire1_BITS__ETC___d14 = 17179869183llu & ((((tUInt64)((tUInt8)1u)) << 32u) | (tUInt64)(DEF_sum__h202));
  INST_result.METH_write(DEF__1_CONCAT_wire0_BITS_31_TO_0_1_PLUS_wire1_BITS__ETC___d14);
  INST_wire0.METH_write(12884901888llu);
  INST_wire1.METH_write(12884901888llu);
  INST_reduced.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,32,32,32",
		   &__str_literal_1,
		   DEF_a__h200,
		   DEF_b__h201,
		   DEF_sum__h202);
}

void MOD_mkIvyAdd::RL_rl_erase()
{
  INST_wire1.METH_write(12884901888llu);
  INST_wire0.METH_write(12884901888llu);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_2);
}


/* Methods */

tUInt8 MOD_mkIvyAdd::METH_done()
{
  tUInt8 PORT_done;
  DEF_reduced__h197 = INST_reduced.METH_read();
  PORT_done = DEF_reduced__h197;
  return PORT_done;
}

tUInt8 MOD_mkIvyAdd::METH_RDY_done()
{
  tUInt8 DEF_CAN_FIRE_done;
  tUInt8 PORT_RDY_done;
  DEF_CAN_FIRE_done = (tUInt8)1u;
  PORT_RDY_done = DEF_CAN_FIRE_done;
  return PORT_RDY_done;
}

tUInt32 MOD_mkIvyAdd::METH_readResult()
{
  tUInt64 DEF_result___d19;
  tUInt32 PORT_readResult;
  DEF_result___d19 = INST_result.METH_read();
  PORT_readResult = (tUInt32)(DEF_result___d19);
  return PORT_readResult;
}

tUInt8 MOD_mkIvyAdd::METH_RDY_readResult()
{
  tUInt8 DEF_CAN_FIRE_readResult;
  tUInt8 PORT_RDY_readResult;
  DEF_reduced__h197 = INST_reduced.METH_read();
  DEF_CAN_FIRE_readResult = DEF_reduced__h197;
  PORT_RDY_readResult = DEF_CAN_FIRE_readResult;
  return PORT_RDY_readResult;
}


/* Reset routines */

void MOD_mkIvyAdd::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_wire1.reset_RST(ARG_rst_in);
  INST_wire0.reset_RST(ARG_rst_in);
  INST_result.reset_RST(ARG_rst_in);
  INST_reduced.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkIvyAdd::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkIvyAdd::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_reduced.dump_state(indent + 2u);
  INST_result.dump_state(indent + 2u);
  INST_wire0.dump_state(indent + 2u);
  INST_wire1.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkIvyAdd::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 8u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "reduced__h197", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "wire0___d1", 34u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "wire1___d4", 34u);
  num = INST_reduced.dump_VCD_defs(num);
  num = INST_result.dump_VCD_defs(num);
  num = INST_wire0.dump_VCD_defs(num);
  num = INST_wire1.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkIvyAdd::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkIvyAdd &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkIvyAdd::vcd_defs(tVCDDumpType dt, MOD_mkIvyAdd &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 34u);
    vcd_write_x(sim_hdl, num++, 34u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_reduced__h197) != DEF_reduced__h197)
      {
	vcd_write_val(sim_hdl, num, DEF_reduced__h197, 1u);
	backing.DEF_reduced__h197 = DEF_reduced__h197;
      }
      ++num;
      if ((backing.DEF_wire0___d1) != DEF_wire0___d1)
      {
	vcd_write_val(sim_hdl, num, DEF_wire0___d1, 34u);
	backing.DEF_wire0___d1 = DEF_wire0___d1;
      }
      ++num;
      if ((backing.DEF_wire1___d4) != DEF_wire1___d4)
      {
	vcd_write_val(sim_hdl, num, DEF_wire1___d4, 34u);
	backing.DEF_wire1___d4 = DEF_wire1___d4;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_reduced__h197, 1u);
      backing.DEF_reduced__h197 = DEF_reduced__h197;
      vcd_write_val(sim_hdl, num++, DEF_wire0___d1, 34u);
      backing.DEF_wire0___d1 = DEF_wire0___d1;
      vcd_write_val(sim_hdl, num++, DEF_wire1___d4, 34u);
      backing.DEF_wire1___d4 = DEF_wire1___d4;
    }
}

void MOD_mkIvyAdd::vcd_prims(tVCDDumpType dt, MOD_mkIvyAdd &backing)
{
  INST_reduced.dump_VCD(dt, backing.INST_reduced);
  INST_result.dump_VCD(dt, backing.INST_result);
  INST_wire0.dump_VCD(dt, backing.INST_wire0);
  INST_wire1.dump_VCD(dt, backing.INST_wire1);
}
