/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Sat May 30 21:26:53 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTestIntNets.h"


/* String declarations */
static std::string const __str_literal_7("FAIL: expected 27, got %0d", 26u);
static std::string const __str_literal_6("PASS: 15 + 12 = 27", 18u);
static std::string const __str_literal_5("[cycle %2d] DONE    result = %0d", 32u);
static std::string const __str_literal_3("[cycle %2d] FIRE    rl_n32_add: vi:ext#2[vi:n32:add](15, 12)",
					 60u);
static std::string const __str_literal_2("[cycle %2d] GUARD   active pair detected: wire0=TAG_N32, wire1=TAG_N32",
					 70u);
static std::string const __str_literal_1("[cycle %2d] INIT    wire0=N32(15)  wire1=N32(12)  result=INVALID",
					 64u);
static std::string const __str_literal_4("[cycle %2d] REWRITE wire0=INVALID  wire1=INVALID  result=N32(27)",
					 64u);


/* Constructor */
MOD_mkTestIntNets::MOD_mkTestIntNets(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_dut(simHdl, "dut", this),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 6u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTestIntNets::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "dut", SYM_MODULE, &INST_dut);
  init_symbol(&symbols[2u], "RL_rl_check", SYM_RULE);
  init_symbol(&symbols[3u], "RL_rl_init", SYM_RULE);
  init_symbol(&symbols[4u], "RL_rl_tick", SYM_RULE);
  init_symbol(&symbols[5u], "x__h119", SYM_DEF, &DEF_x__h119, 32u);
}


/* Rule actions */

void MOD_mkTestIntNets::RL_rl_tick()
{
  tUInt32 DEF_x__h107;
  DEF_x__h119 = INST_cycle.METH_read();
  DEF_x__h107 = DEF_x__h119 + 1u;
  INST_cycle.METH_write(DEF_x__h107);
}

void MOD_mkTestIntNets::RL_rl_init()
{
  DEF_x__h119 = INST_cycle.METH_read();
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF_x__h119);
    dollar_display(sim_hdl, this, "s,32", &__str_literal_2, DEF_x__h119);
    dollar_display(sim_hdl, this, "s,32", &__str_literal_3, DEF_x__h119);
    dollar_display(sim_hdl, this, "s,32", &__str_literal_4, DEF_x__h119);
  }
}

void MOD_mkTestIntNets::RL_rl_check()
{
  tUInt8 DEF_NOT_dut_readResult_EQ_27___d9;
  tUInt8 DEF_dut_readResult_EQ_27___d8;
  tUInt32 DEF_r__h229;
  DEF_x__h119 = INST_cycle.METH_read();
  DEF_r__h229 = INST_dut.METH_readResult();
  DEF_dut_readResult_EQ_27___d8 = DEF_r__h229 == 27u;
  DEF_NOT_dut_readResult_EQ_27___d9 = !DEF_dut_readResult_EQ_27___d8;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s,32,32", &__str_literal_5, DEF_x__h119, DEF_r__h229);
    if (DEF_dut_readResult_EQ_27___d8)
      dollar_display(sim_hdl, this, "s", &__str_literal_6);
    if (DEF_NOT_dut_readResult_EQ_27___d9)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_7, DEF_r__h229);
    dollar_finish(sim_hdl, "32", 1u);
  }
}


/* Methods */


/* Reset routines */

void MOD_mkTestIntNets::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_dut.reset_RST_N(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTestIntNets::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTestIntNets::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_dut.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTestIntNets::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 3u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h119", 32u);
  num = INST_cycle.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_dut.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTestIntNets::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTestIntNets &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkTestIntNets::vcd_defs(tVCDDumpType dt, MOD_mkTestIntNets &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_x__h119) != DEF_x__h119)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h119, 32u);
	backing.DEF_x__h119 = DEF_x__h119;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_x__h119, 32u);
      backing.DEF_x__h119 = DEF_x__h119;
    }
}

void MOD_mkTestIntNets::vcd_prims(tVCDDumpType dt, MOD_mkTestIntNets &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
}

void MOD_mkTestIntNets::vcd_submodules(tVCDDumpType dt,
				       unsigned int levels,
				       MOD_mkTestIntNets &backing)
{
  INST_dut.dump_VCD(dt, levels, backing.INST_dut);
}
