/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Sun May 31 19:52:54 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkTestIntNets_h__
#define __mkTestIntNets_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkIvyAdd.h"


/* Class declaration for the mkTestIntNets module */
class MOD_mkTestIntNets : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycle;
  MOD_mkIvyAdd INST_dut;
 
 /* Constructor */
 public:
  MOD_mkTestIntNets(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt32 DEF_x__h119;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_rl_tick();
  void RL_rl_init();
  void RL_rl_check();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTestIntNets &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTestIntNets &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTestIntNets &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTestIntNets &backing);
};

#endif /* ifndef __mkTestIntNets_h__ */
