/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Sun May 31 19:52:54 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTestIntNets.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTestIntNets::MODEL_mkTestIntNets()
{
  mkTestIntNets_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTestIntNets()
{
  MODEL_mkTestIntNets *model = new MODEL_mkTestIntNets();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTestIntNets &INST_top = *((MOD_mkTestIntNets *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_dut_DEF_wire1_BITS_33_TO_32___d5;
	 tUInt8 DEF_INST_top_INST_dut_DEF_wire0_BITS_33_TO_32___d2;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_n32_add;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_n32_add;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_erase;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_erase;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_tick;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_tick;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_init;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_init;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_check;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_check;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_check = INST_top.INST_dut.METH_RDY_readResult() && INST_top.INST_dut.METH_done();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_check = DEF_INST_top_DEF_CAN_FIRE_RL_rl_check;
	 INST_top.DEF_x__h119 = INST_top.INST_cycle.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_init = (INST_top.DEF_x__h119) == 0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_init = DEF_INST_top_DEF_CAN_FIRE_RL_rl_init;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_tick = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_tick = DEF_INST_top_DEF_CAN_FIRE_RL_rl_tick;
	 INST_top.INST_dut.DEF_wire1___d4 = INST_top.INST_dut.INST_wire1.METH_read();
	 INST_top.INST_dut.DEF_wire0___d1 = INST_top.INST_dut.INST_wire0.METH_read();
	 DEF_INST_top_INST_dut_DEF_wire0_BITS_33_TO_32___d2 = (tUInt8)((INST_top.INST_dut.DEF_wire0___d1) >> 32u);
	 DEF_INST_top_INST_dut_DEF_wire1_BITS_33_TO_32___d5 = (tUInt8)((INST_top.INST_dut.DEF_wire1___d4) >> 32u);
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_erase = DEF_INST_top_INST_dut_DEF_wire0_BITS_33_TO_32___d2 == (tUInt8)2u && !(DEF_INST_top_INST_dut_DEF_wire1_BITS_33_TO_32___d5 == (tUInt8)3u);
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_erase = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_erase;
	 INST_top.INST_dut.DEF_reduced__h197 = INST_top.INST_dut.INST_reduced.METH_read();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_n32_add = (DEF_INST_top_INST_dut_DEF_wire0_BITS_33_TO_32___d2 == (tUInt8)1u && DEF_INST_top_INST_dut_DEF_wire1_BITS_33_TO_32___d5 == (tUInt8)1u) && !(INST_top.INST_dut.DEF_reduced__h197);
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_n32_add = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_n32_add;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_init)
	   INST_top.RL_rl_init();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_check)
	   INST_top.RL_rl_check();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_tick)
	   INST_top.RL_rl_tick();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_erase)
	   INST_top.INST_dut.RL_rl_erase();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_n32_add)
	   INST_top.INST_dut.RL_rl_n32_add();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut.INST_wire0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_wire1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_result.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_reduced.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTestIntNets::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTestIntNets_instance = new MOD_mkTestIntNets(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTestIntNets_instance->INST_dut.set_clk_0)("CLK");
  (mkTestIntNets_instance->set_clk_0)("CLK");
}
void MODEL_mkTestIntNets::destroy_model()
{
  delete mkTestIntNets_instance;
  mkTestIntNets_instance = NULL;
}
void MODEL_mkTestIntNets::reset_model(bool asserted)
{
  (mkTestIntNets_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTestIntNets::get_instance()
{
  return mkTestIntNets_instance;
}

/* Fill in version numbers */
void MODEL_mkTestIntNets::get_version(char const **name, char const **build)
{
  *name = "2026.01";
  *build = "9bd39e6f";
}

/* Get the model creation time */
time_t MODEL_mkTestIntNets::get_creation_time()
{
  
  /* Sun May 31 18:52:54 UTC 2026 */
  return 1780253574llu;
}

/* State dumping function */
void MODEL_mkTestIntNets::dump_state()
{
  (mkTestIntNets_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTestIntNets & mkTestIntNets_backing(tSimStateHdl simHdl)
{
  static MOD_mkTestIntNets *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTestIntNets(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTestIntNets::dump_VCD_defs()
{
  (mkTestIntNets_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTestIntNets::dump_VCD(tVCDDumpType dt)
{
  (mkTestIntNets_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTestIntNets_backing(sim_hdl));
}
