/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Sat May 30 21:26:53 BST 2026
 * 
 */

/* Generation options: */
#ifndef __model_mkTestIntNets_h__
#define __model_mkTestIntNets_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTestIntNets.h"

/* Class declaration for a model of mkTestIntNets */
class MODEL_mkTestIntNets : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTestIntNets *mkTestIntNets_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTestIntNets();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTestIntNets();
}

#endif /* ifndef __model_mkTestIntNets_h__ */
